# Exported from Render on 2025-08-30T04:45:04Z
services:
- type: web
  name: ragestream
  runtime: node
  repo: https://github.com/Blazebat/studious-enigma
  plan: free
  region: oregon
  buildCommand: yarn install
  startCommand: node index.js
  autoDeployTrigger: commit
version: "1"
